import React from 'react'
import NavSidebar from '../components/NavSidebar'

const ManajemenPengguna = ({ isSidebarOpen }) => {
    return (
      <div className={`bg-ungu10 pt-14 w-full h-full transition-all duration-300 ${isSidebarOpen ? 'ml-16 md:ml-64' : 'ml-0'}`}>
          <p className="px-6">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Error rerum asperiores eius fugit dignissimos. Iusto doloribus porro, aliquid, et error distinctio corporis sint perferendis praesentium mollitia quas in animi quae? Fugit adipisci optio voluptas. Modi nostrum qui repudiandae ea voluptas harum exercitationem ab nihil esse debitis blanditiis reprehenderit earum laboriosam labore voluptate placeat, eveniet consectetur ducimus autem voluptatum totam. Consectetur aperiam itaque aspernatur expedita, laudantium consequatur placeat voluptatem facere iure, numquam praesentium veritatis. Sunt unde delectus mollitia odio provident temporibus totam iste laborum, a perferendis ipsum atque, quidem sapiente est. A aperiam provident officia corrupti natus praesentium sed, eligendi sit dolore deserunt commodi tempore molestias distinctio, expedita perferendis quisquam enim cumque, laudantium iure exercitationem ratione eum repudiandae perspiciatis! Placeat quis excepturi qui facilis. Nihil quam vel odit repellat? Libero repudiandae, eos eaque molestiae expedita ab dolores suscipit, natus temporibus quaerat est perspiciatis recusandae, quis quidem voluptatem aliquam et eveniet aperiam sapiente tempore quod voluptates voluptatum nam. Ratione, officia vitae minus perspiciatis architecto dolorum suscipit quod dolorem consequuntur quis. Placeat beatae voluptatem esse quia at laboriosam praesentium nobis eligendi. Facere fuga sint qui dicta deleniti ullam, quam accusamus, atque commodi in iste dolorem veniam fugit voluptatibus. Necessitatibus explicabo molestiae, quod inventore doloribus eaque tenetur voluptates doloremque omnis, reiciendis, quia quos maxime? Odio, hic fuga reiciendis alias rem vel pariatur deserunt nulla natus recusandae neque iste asperiores explicabo veniam inventore expedita officiis, aut aliquid voluptates architecto suscipit ducimus! Sint tempore vel quo consectetur hic maxime beatae culpa iure animi possimus enim eaque omnis incidunt illo repellendus, nobis quisquam consequuntur sit voluptatum praesentium blanditiis. Eveniet, quos repellat soluta libero, iusto excepturi assumenda officia quisquam, veritatis porro atque! Nihil eos dolorem nostrum amet officiis, distinctio culpa perferendis sunt quisquam quam itaque assumenda illo obcaecati explicabo inventore reiciendis perspiciatis sed velit hic ipsa! Blanditiis, a.
          </p>
      </div>
    );
  };

export default ManajemenPengguna